output "o_pet_name" {
  description = "Pet name generated by the random provider"
  value = random_pet.pet.id
}

output "o_uuid" {
  description = "UUID generated by the random provider"
  value = random_uuid.uuid.result
}