name: Deploy App

on:
  push:
    branches: [master, dev]

env:
  AZURE_WEBAPP_PATH: './DotnetCD'
  DOTNET_VERSION: '5.0.x'

  # For Terraform's azurerm provider
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      sku_tier: ${{ initialize_vars.outputs.sku_tier }}
      sku_size: ${{ initialize_vars.outputs.sku_size }}
      site_config_use_32_bit_worker_process: ${{ initialize_vars.outputs.site_config_use_32_bit_worker_process }}
    steps:
      - name: Initialize Branch Variable
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e "s#refs/heads/##g")" >> $GITHUB_ENV

      - id: initialize_vars
        name: Initialize Variables
        run: |
          if [[ $BRANCH_NAME == 'master' ]]; then
            echo '::set-output name=sku_tier::Standard'
            echo '::set-output name=sku_size::S1'
            echo '::set-output name=site_config_use_32_bit_worker_process=false'
          else
            echo '::set-output name=sku_tier::Free'
            echo '::set-output name=sku_size::F1'
            echo '::set-output name=site_config_use_32_bit_worker_process=true'
          fi
      

  setup-infra:
    needs: set-vars
    runs-on: ubuntu-latest
    outputs: 
      app_service_name: ${{ steps.terraform_output.outputs.app_service_name }}
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init \
          -backend-config="access_key=${{ secrets.TFB_ACCESS_KEY }}" \
          -backend-config="resource_group_name=${{ secrets.TFB_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.TFB_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.TFB_CONTAINER_NAME }}"
        
      - name: Terraform Workspace Select
        run: terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME
      
      - name: Terraform Apply
        run: terraform apply \
          -var='branch_name=$BRANCH_NAME' \
          -var='app_service_plan_sku={"tier":"${{ needs.set_vars.outputs.sku_tier }}","size":"${{ needs.set_vars.outputs.sku_size }}"}' \
          -var='app_service_site_config_use_32_bit_worker_process=${{ needs.set_vars.outputs.site_config_use_32_bit_worker_process }}'
          -auto-approve

      - id: terraform_output
        run: echo "::set-output name=app_service_name::$(terraform output -raw app_service_name)"
        
  build-and-deploy:
    needs: setup-infra
    runs-on: windows-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-restore -o '${{ env.AZURE_WEBAPP_PATH }}'

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ needs.setup-infra.outputs.app_service_name }}'
          package: '${{ env.AZURE_WEBAPP_PATH }}'
      
      - name: Azure Logout
        run: az logout